language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test
after_script:
- npm run coverage
deploy:
  provider: npm
  email: bas@strootje.com
  api_key:
    secure: hAbietF3wOzHUi8lC/L0ec3qzg9+Yk07Y7NP4NNwSOIv7t+hFsy4POpFmAVDu8Vv4ojPCl7R+AMh+pB8y8hIOSCa2YUePaCCM55jf0xEvBhvAl3VLbE1/294hJUI7wQBm8cpMbTE6TbHOUaKuUSzIGUdob0EMejXKKd+sfXxsFaBNo0IJf6/BkBgpZ06ae2uBRv6vz7AIDHGt7jpgBiFdB2qkqtZ9qFj5DrS/XL7MpYbFLe78b3WlguszjSg9hrDVyhJCe6mlPwuzgURazfrjR+NyzRR7Jy5BxSd1jmi7EC7jc/ZaU63uvBZRVDODQEyN9XrazGiEVMwFNxsBdaDFPMs0/PC6Xx/tqXnJTef7IUSHGD0jO3F0ylx548E7Afo8S4JuKds5WA6o7LzrfAIjRGTaTPwemz9qy6BvZmQKtFWnlMVRt+J7Srs3HMQDODUYE74utRDp2e8AEcJ94sRnCDXha/yd1keKD5qCLqa03VeCXiLA1c3PI0+OmIebmZx56hMKdBZDS6Qj8JPrQ1+NGMOxt9UFekuHzuzJd5TMP4fOCqBPg4jN1f+Llmw0YLAMmBMddgmonKcZnBBJpMQvWqwRO7A8OQijnu/WhY7FImPPQfq/t12Fwy46+8ReSNkg8aMR34JlvYCPwm2UNjXvlvfxenEW2Qr4znXEyXjxIQ=
  on:
    tags: true
    repo: strootje/vue-component-loader
